views:
  - name: orders_view

    cubes:
      - join_path: orders
        includes:
          - status
          - created_at
          - id

          - completed_count
          - count
          - total_amount
          - average_order_value

      - join_path: orders.users
        prefix: true
        includes: 
          - city
          - age
          - gender
          - last_name

      - join_path: orders.line_items.products
        prefix: true
        includes: 
          - product_category