cubes:
  - name: product_categories
    sql: SELECT * FROM public.product_categories
    shown: false
      
    measures:
      - name: count
        type: count
    
    dimensions:
      - name: id
        sql: id
        type: number
        primaryKey: true

      - name: name
        sql: name
        type: string
        
      - name: created_date
        sql: created_at
        type: time
