cubes:
  - name: products
    sql_table: ecom.products
    public: false

    measures:
      - name: count
        type: count

    dimensions:
      - name: id
        sql: id
        type: number
        primaryKey: true

      - name: name
        sql: name
        type: string

      - name: product_category
        sql: product_category
        type: string
        
      - name: created_at
        sql: created_at
        type: time
