views:
  - name: customers
    description: "Users who placed at least one order"

    cubes:
      - join_path: users
        includes:    
          # dimensions
          - signup_date
          - most_recent_order_date
          - number_of_orders
          - name: customers_count
            alias: count

          # measures
          - total_orders_amount
          - average_lifetime_value