views:
  - name: orders_view

    cubes:
      - join_path: orders
        includes:
          - status
          - created_at

          - completed_count
          # - completed_percentage
          - count
          - total_amount
          - average_order_value

      - join_path: orders.users
        prefix: true
        includes:
          - first_name
          - last_name 
          - city
          - age
          - gender