views:
  - name: customers
    description: "Users who placed at least one order"

    cubes:
      - cube: users
        includes:    
          # dimensions
          - signup_date
          - most_recent_order_date
          - number_of_orders
          - member: customers_count
            name: count_test

          # measures
          - total_orders_amount
          - average_lifetime_value