views:
  - name: orders

    cubes:
      - join_path: base_orders
        includes:
          # dimensions
          - status
          - created_date

          # measures
          - total_amount
          - total_amlunt_shipped
          - count
          - average_order_value
      
      - join_path: base_orders.line_items.products
        includes: 
          - name: name
            alias: product

      - join_path: base_orders.line_items.products.product_categories
        includes: 
          - name: name
            alias: product_category

      - join_path: base_orders.users
        prefix: true
        includes: 
          - city