views:
  - name: orders

    cubes:
      - cube: base_orders
        includes:
          # dimensions
          - status
          - created_date

          # measures
          - total_amount
          - total_amlunt_shipped
          - count
          - average_order_value
      
      - cube: base_orders.line_items.products
        includes: 
          - member: name
            name: product

      - cube: base_orders.line_items.products.product_categories
        includes: 
          - member: name
            name: product_category

      - cube: base_orders.users
        prefix: true
        includes: 
          - city