cubes:
  - name: ProductCategories
    sql: SELECT * FROM public.product_categories
      # preAggregations:
      # Pre-Aggregations definitions go here
      # Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started
    joins: []
    measures:
      - name: count
        type: count
        drillMembers: [id, name, createdAt]
    dimensions:
      - name: id
        sql: id
        type: number
        primaryKey: true
      - name: name
        sql: name
        type: string
      - name: createdAt
        sql: created_at
        type: time
